---
# Cloudwatch Exporter metrics configuration (cloudwatch_metrics.yml)
cloudwatch_metrics_enable: true
auto_scaling: no
billing: no
custom: no
dynamo_db: true
ebs: true
ec2: true
elasti_cache: true
events: true
lambda: true
logs: true
network_elb: true
rds: true
s3: true
transit_gateway: true
trusted_advisor: true
usage: true
